
spring:
  application:
    name: spring-profile-poc
  profiles:
    active: prod

smpp:
  host: localhost
  port: 2775
#  systemId: smppclient1
#  password: password
  systemId: ${systemId}
  password: ${password}
  enquireLinkTimer: 30000
  transactionTimer: 30000
